#!/bin/sh

# Source Xresources - Xdefaults
xrdb ~/.Xresources &

# Setup monitors
# screens &
# sleep 2 &&

# Nitrogen
nitrogen --restore &

# Mate polkit agent for auth
/usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1 &

# Make sure Dunst gets started
/usr/bin/dunst &

# Compton - Picom
sleep 1 &&
compton -b
