#!/bin/sh

# Source Xresources / Xdefaults
xrdb ~/.Xresources &

# Setup monitors
screens &

# Use Nitrogen instead of icewmbg
sleep 2 &&
nitrogen --restore &

# Gnome polkit agent
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
