#!/bin/sh

# Setup monitors
#screens &
#sleep 2 &&

# Xresources - Xdefaults
xrdb ~/.Xresources &

# xsettings daemon
xsettingsd &

# Mate polkit agent for authentication
/usr/lib/x86_64-linux-gnu/polkit-mate/polkit-mate-authentication-agent-1 &

# Nitrogen
nitrogen --restore &

# Make sure Dunst gets started
dunst &

# GNOME
nm-applet &

# KDE connect
kdeconnect-indicator &

# Compton - Picom
compton -b
