#!/bin/sh

# Monitor script
#sleep 1;screens;sleep 1 &

# Xresources - Xdefaults
xrdb ~/.Xresources &

# xsettings daemon
xsettingsd -c ~/.config/xsettingsd &

# Nitrogen
nitrogen --restore &

# Mate polkit agent for authentication prompts
/usr/bin/lxpolkit &

# GNOME network manager applet
nm-applet &

# KDE connect
kdeconnect-indicator &

# Compton - Picom
compton -b &
